// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonmezERP.Data;

#nullable disable

namespace SonmezERP.Migrations
{
    [DbContext(typeof(SonmezERPContext))]
    partial class SonmezERPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SonmezERP.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Container")
                        .HasColumnType("int");

                    b.Property<string>("Coordinate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CubicMeter")
                        .HasColumnType("real");

                    b.Property<int>("PackageHight")
                        .HasColumnType("int");

                    b.Property<int>("PackagePices")
                        .HasColumnType("int");

                    b.Property<int>("PackageSize")
                        .HasColumnType("int");

                    b.Property<int>("PackageWidth")
                        .HasColumnType("int");

                    b.Property<float>("PriceTl")
                        .HasColumnType("real");

                    b.Property<float>("PriceUSD")
                        .HasColumnType("real");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductHight")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNameTr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductSize")
                        .HasColumnType("int");

                    b.Property<float>("ProductWeight")
                        .HasColumnType("real");

                    b.Property<int>("ProductWidth")
                        .HasColumnType("int");

                    b.Property<int>("Tir")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
